language: node_js

notifications:
    email:
        - aralejs@gmail.com

node_js:
  - 0.8

install: 
  - npm install nico
  - npm install spm
  - npm install mocha-phantomjs
  - ./node_modules/.bin/spm install

before_script:
  - git clone https://github.com/aralejs/nico-arale.git _theme
  - nohup ./node_modules/.bin/nico server -q -C _theme/nico.js debug &

script: ./node_modules/.bin/mocha-phantomjs http://127.0.0.1:8000/tests/runner.html
