language: node_js

notifications:
    email:
        - aralejs@gmail.com

node_js:
  - 0.8

before_script:
  - git clone https://github.com/aralejs/nico-arale.git ../nico-arale
  - cp -r ../nico-arale/static tests/
  - mkdir tests/templates
  - cp ../nico-arale/templates/mocha-runner.html tests/templates/runner.html
  - cp -r ../nico-arale/test-travis.js tests/
  - nohup node tests/test-travis.js &

install: 
  - npm install spm node-static swig mocha-phantomjs
  - spm install

script: ./node_modules/.bin/mocha-phantomjs http://127.0.0.1:8000/tests/runner.html
